"""empty message

Revision ID: 2c66a2eadb6c
Revises: 8c0996e96073
Create Date: 2024-10-09 14:08:00.860715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c66a2eadb6c'
down_revision = '8c0996e96073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
        batch_op.alter_column('completed', nullable =False)  

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
